//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumers
    {
        public Consumers()
        {
            this.Consumption = new HashSet<Consumption>();
            this.WellProduction = new HashSet<WellProduction>();
        }
    
        public int IDConsumer { get; set; }
        public string Name { get; set; }
        public string UWI { get; set; }
        public string InternalOrder { get; set; }
        public int IDMapElementType { get; set; }
        public int IDCostCenter { get; set; }
        public int IDDistrict { get; set; }
        public Nullable<int> IDFieldCluster { get; set; }
        public Nullable<int> IDElectricStation { get; set; }
        public Nullable<int> IDPowerTransformer { get; set; }
        public string Address { get; set; }
        public Nullable<int> InstalledPower { get; set; }
        public Nullable<int> NormalOperation { get; set; }
        public string VMSCode { get; set; }
        public Nullable<int> NominalVoltage { get; set; }
        public Nullable<int> IDDataSource { get; set; }
        public int ComputingSign { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual Consumers Consumers1 { get; set; }
        public virtual Consumers Consumers2 { get; set; }
        public virtual MapElementTypes MapElementTypes { get; set; }
        public virtual CostCenters CostCenters { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual ElectricStations ElectricStations { get; set; }
        public virtual FieldClusters FieldClusters { get; set; }
        public virtual MapElementTypes MapElementTypes1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ICollection<Consumption> Consumption { get; set; }
        public virtual ICollection<WellProduction> WellProduction { get; set; }
    }
}
