//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumption
    {
        public Consumption()
        {
            this.ConsumptionDetails = new HashSet<ConsumptionDetails>();
        }
    
        public int IDConsumption { get; set; }
        public int IDConsumer { get; set; }
        public System.DateTime ConsumptionDate { get; set; }
        public int ActiveEnergyIndex { get; set; }
        public Nullable<int> InductiveEnergyIndex { get; set; }
        public Nullable<int> CapacitiveEnergyIndex { get; set; }
        public Nullable<int> ActiveEnergyCorrection { get; set; }
        public Nullable<int> InductiveEnergyCorrection { get; set; }
        public Nullable<int> CapacitiveEnergyCorrection { get; set; }
        public Nullable<int> Voltage { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Consumers Consumers { get; set; }
        public virtual ICollection<ConsumptionDetails> ConsumptionDetails { get; set; }
    }
}
