//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenters
    {
        public CostCenters()
        {
            this.Consumers = new HashSet<Consumers>();
            this.CostCenters1 = new HashSet<CostCenters>();
        }
    
        public int IDCostCenter { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }
        public Nullable<int> IDParentCostCenter { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<Consumers> Consumers { get; set; }
        public virtual ICollection<CostCenters> CostCenters1 { get; set; }
        public virtual CostCenters CostCenters2 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
