//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricalThresholds
    {
        public int IDElectricalThreshold { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> MinimumValue { get; set; }
        public Nullable<decimal> MaximumValue { get; set; }
        public int SuccessiveOccurrences { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual ElectricalThresholds ElectricalThresholds1 { get; set; }
        public virtual ElectricalThresholds ElectricalThresholds2 { get; set; }
    }
}
