//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricLines
    {
        public ElectricLines()
        {
            this.FiscalMeters = new HashSet<FiscalMeters>();
            this.GPSCoordinates = new HashSet<GPSCoordinates>();
            this.PowerTransformers = new HashSet<PowerTransformers>();
        }
    
        public int IDElectricLine { get; set; }
        public string Name { get; set; }
        public int IDVoltageLevel { get; set; }
        public int IDAsset { get; set; }
        public Nullable<int> IDDistrict { get; set; }
        public Nullable<int> IDMapElementType { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Active { get; set; }
        public ElectricLineCapacityEnum Capacity { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Districts Districts { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual VoltageLevels VoltageLevels { get; set; }
        public virtual ICollection<FiscalMeters> FiscalMeters { get; set; }
        public virtual ICollection<GPSCoordinates> GPSCoordinates { get; set; }
        public virtual ICollection<PowerTransformers> PowerTransformers { get; set; }
    }
}
