//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyInput
    {
        public int IDEnergyInput { get; set; }
        public int IDFiscalMeter { get; set; }
        public System.DateTime InputDate { get; set; }
        public Nullable<int> ActiveEnergyIndex { get; set; }
        public Nullable<int> InductiveEnergyIndex { get; set; }
        public Nullable<int> CapacitiveEnergyIndex { get; set; }
        public Nullable<int> ActiveEnergyCorrection { get; set; }
        public Nullable<int> InductiveEnergyCorrection { get; set; }
        public Nullable<int> CapacitiveEnergyCorrection { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual FiscalMeters FiscalMeters { get; set; }
        public virtual Users Users { get; set; }
    }
}
