//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FanicaCGEntities : DbContext
    {
        public FanicaCGEntities()
            : base("name=FanicaCGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Assets> Assets { get; set; }
        public DbSet<Capacitors> Capacitors { get; set; }
        public DbSet<CapacitorTypes> CapacitorTypes { get; set; }
        public DbSet<Consumers> Consumers { get; set; }
        public DbSet<Consumption> Consumption { get; set; }
        public DbSet<ConsumptionDetails> ConsumptionDetails { get; set; }
        public DbSet<CostCenters> CostCenters { get; set; }
        public DbSet<DataSources> DataSources { get; set; }
        public DbSet<Districts> Districts { get; set; }
        public DbSet<ElectricalTariffs> ElectricalTariffs { get; set; }
        public DbSet<ElectricalThresholds> ElectricalThresholds { get; set; }
        public DbSet<ElectricLines> ElectricLines { get; set; }
        public DbSet<ElectricStations> ElectricStations { get; set; }
        public DbSet<EnergyInput> EnergyInput { get; set; }
        public DbSet<FieldClusters> FieldClusters { get; set; }
        public DbSet<FiscalMeters> FiscalMeters { get; set; }
        public DbSet<GPSCoordinates> GPSCoordinates { get; set; }
        public DbSet<ImportFiles> ImportFiles { get; set; }
        public DbSet<Imports> Imports { get; set; }
        public DbSet<ImportTypes> ImportTypes { get; set; }
        public DbSet<MapElementLinks> MapElementLinks { get; set; }
        public DbSet<MapElementsToMapElementLinks> MapElementsToMapElementLinks { get; set; }
        public DbSet<MapElementTypes> MapElementTypes { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<MenuToRoles> MenuToRoles { get; set; }
        public DbSet<Months> Months { get; set; }
        public DbSet<NetworkOperators> NetworkOperators { get; set; }
        public DbSet<NotificationRules> NotificationRules { get; set; }
        public DbSet<Notifications> Notifications { get; set; }
        public DbSet<NotificationsToUsers> NotificationsToUsers { get; set; }
        public DbSet<PowerTransformers> PowerTransformers { get; set; }
        public DbSet<PowerTransformersToElectricLines> PowerTransformersToElectricLines { get; set; }
        public DbSet<Reports> Reports { get; set; }
        public DbSet<ReportsToRoles> ReportsToRoles { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersToRoles> UsersToRoles { get; set; }
        public DbSet<VoltageLevels> VoltageLevels { get; set; }
        public DbSet<WellProduction> WellProduction { get; set; }
        public DbSet<MapElectricLines> MapElectricLines { get; set; }
        public DbSet<MapElements> MapElements { get; set; }
    }
}
