//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public Notifications()
        {
            this.NotificationsToUsers = new HashSet<NotificationsToUsers>();
        }
    
        public int IDNotification { get; set; }
        public Nullable<int> IDNotificationRule { get; set; }
        public string NotificationSubject { get; set; }
        public string NotificationBody { get; set; }
        public System.DateTime NotificationStartDate { get; set; }
        public System.DateTime NotificationEndDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual NotificationRules NotificationRules { get; set; }
        public virtual ICollection<NotificationsToUsers> NotificationsToUsers { get; set; }
    }
}
