//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.MenuToRoles = new HashSet<MenuToRoles>();
            this.ReportsToRoles = new HashSet<ReportsToRoles>();
            this.UsersToRoles = new HashSet<UsersToRoles>();
        }
    
        public int IDRole { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<MenuToRoles> MenuToRoles { get; set; }
        public virtual ICollection<ReportsToRoles> ReportsToRoles { get; set; }
        public virtual ICollection<UsersToRoles> UsersToRoles { get; set; }
    }
}
