//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Assets = new HashSet<Assets>();
            this.Assets1 = new HashSet<Assets>();
            this.Capacitors = new HashSet<Capacitors>();
            this.Capacitors1 = new HashSet<Capacitors>();
            this.Capacitors2 = new HashSet<Capacitors>();
            this.CapacitorTypes = new HashSet<CapacitorTypes>();
            this.CapacitorTypes1 = new HashSet<CapacitorTypes>();
            this.Consumers = new HashSet<Consumers>();
            this.Consumers1 = new HashSet<Consumers>();
            this.ConsumptionDetails = new HashSet<ConsumptionDetails>();
            this.ConsumptionDetails1 = new HashSet<ConsumptionDetails>();
            this.CostCenters = new HashSet<CostCenters>();
            this.CostCenters1 = new HashSet<CostCenters>();
            this.ElectricLines = new HashSet<ElectricLines>();
            this.ElectricLines1 = new HashSet<ElectricLines>();
            this.EnergyInput = new HashSet<EnergyInput>();
            this.FiscalMeters = new HashSet<FiscalMeters>();
            this.FiscalMeters1 = new HashSet<FiscalMeters>();
            this.GPSCoordinates = new HashSet<GPSCoordinates>();
            this.GPSCoordinates1 = new HashSet<GPSCoordinates>();
            this.Imports = new HashSet<Imports>();
            this.Menu = new HashSet<Menu>();
            this.Menu1 = new HashSet<Menu>();
            this.MenuToRoles = new HashSet<MenuToRoles>();
            this.MenuToRoles1 = new HashSet<MenuToRoles>();
            this.NotificationRules = new HashSet<NotificationRules>();
            this.NotificationRules1 = new HashSet<NotificationRules>();
            this.NotificationsToUsers = new HashSet<NotificationsToUsers>();
            this.PowerTransformers = new HashSet<PowerTransformers>();
            this.PowerTransformers1 = new HashSet<PowerTransformers>();
            this.Reports = new HashSet<Reports>();
            this.UsersToRoles = new HashSet<UsersToRoles>();
            this.UsersToRoles1 = new HashSet<UsersToRoles>();
            this.WellProduction = new HashSet<WellProduction>();
        }
    
        public int IDUser { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Assets> Assets { get; set; }
        public virtual ICollection<Assets> Assets1 { get; set; }
        public virtual ICollection<Capacitors> Capacitors { get; set; }
        public virtual ICollection<Capacitors> Capacitors1 { get; set; }
        public virtual ICollection<Capacitors> Capacitors2 { get; set; }
        public virtual ICollection<CapacitorTypes> CapacitorTypes { get; set; }
        public virtual ICollection<CapacitorTypes> CapacitorTypes1 { get; set; }
        public virtual ICollection<Consumers> Consumers { get; set; }
        public virtual ICollection<Consumers> Consumers1 { get; set; }
        public virtual ICollection<ConsumptionDetails> ConsumptionDetails { get; set; }
        public virtual ICollection<ConsumptionDetails> ConsumptionDetails1 { get; set; }
        public virtual ICollection<CostCenters> CostCenters { get; set; }
        public virtual ICollection<CostCenters> CostCenters1 { get; set; }
        public virtual ICollection<ElectricLines> ElectricLines { get; set; }
        public virtual ICollection<ElectricLines> ElectricLines1 { get; set; }
        public virtual ICollection<EnergyInput> EnergyInput { get; set; }
        public virtual ICollection<FiscalMeters> FiscalMeters { get; set; }
        public virtual ICollection<FiscalMeters> FiscalMeters1 { get; set; }
        public virtual ICollection<GPSCoordinates> GPSCoordinates { get; set; }
        public virtual ICollection<GPSCoordinates> GPSCoordinates1 { get; set; }
        public virtual ICollection<Imports> Imports { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<Menu> Menu1 { get; set; }
        public virtual ICollection<MenuToRoles> MenuToRoles { get; set; }
        public virtual ICollection<MenuToRoles> MenuToRoles1 { get; set; }
        public virtual ICollection<NotificationRules> NotificationRules { get; set; }
        public virtual ICollection<NotificationRules> NotificationRules1 { get; set; }
        public virtual ICollection<NotificationsToUsers> NotificationsToUsers { get; set; }
        public virtual ICollection<PowerTransformers> PowerTransformers { get; set; }
        public virtual ICollection<PowerTransformers> PowerTransformers1 { get; set; }
        public virtual ICollection<Reports> Reports { get; set; }
        public virtual ICollection<UsersToRoles> UsersToRoles { get; set; }
        public virtual ICollection<UsersToRoles> UsersToRoles1 { get; set; }
        public virtual ICollection<WellProduction> WellProduction { get; set; }
    }
}
