//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellProduction
    {
        public int IDWellProduction { get; set; }
        public int IDConsumer { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public Nullable<int> RunningHours { get; set; }
        public decimal GrossProduction { get; set; }
        public decimal WaterCut { get; set; }
        public decimal NetOil { get; set; }
        public decimal GasProduction { get; set; }
        public decimal Water { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Consumers Consumers { get; set; }
        public virtual Users Users { get; set; }
    }
}
