//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcquisitionPrice
    {
        public int IDAcquisitionPrice { get; set; }
        public int IDNetworkOperator { get; set; }
        public decimal ActiveEnergyPrice { get; set; }
        public decimal ReactiveMTEnergyPrice { get; set; }
        public decimal ReactiveJTEnergyPrice { get; set; }
        public decimal TL { get; set; }
        public decimal SS { get; set; }
        public decimal OPCOM { get; set; }
        public decimal IT { get; set; }
        public decimal MT { get; set; }
        public decimal JT { get; set; }
        public decimal BalancingCost { get; set; }
        public decimal ProviderProfit { get; set; }
        public decimal CogenerationContribution { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Active { get; set; }
    
        public virtual NetworkOperator NetworkOperator { get; set; }
    }
}
