//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerTypeInfoLink
    {
        public int IDConsumerType { get; set; }
        public int IDConsumerInfoLink { get; set; }
    
        public virtual ConsumerType ConsumerType { get; set; }
        public virtual ConsumerInfoLink ConsumerInfoLink { get; set; }
    }
}
