//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumption
    {
        public Consumption()
        {
            this.ConsumptionDetails = new HashSet<ConsumptionDetail>();
        }
    
        public int IDConsumption { get; set; }
        public int IDConsumer { get; set; }
        public Nullable<decimal> ActiveEnergyMeterStartIndex { get; set; }
        public Nullable<decimal> ActiveEnergyMeterEndIndex { get; set; }
        public decimal ActiveEnergyConsumption { get; set; }
        public Nullable<decimal> InductiveEnergyMeterStartIndex { get; set; }
        public Nullable<decimal> InductiveEnergyMeterEndIndex { get; set; }
        public decimal InductiveEnergyConsumption { get; set; }
        public Nullable<decimal> CapacitiveEnergyMeterStartIndex { get; set; }
        public Nullable<decimal> CapacitiveEnergyMeterEndIndex { get; set; }
        public decimal CapacitiveEnergyConsumption { get; set; }
        public bool UseActiveEnergyCorrection { get; set; }
        public bool UseInductiveEnergyCorrection { get; set; }
        public bool UseCapacitiveEnergyCorrection { get; set; }
        public System.DateTime ConsumptionDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual ICollection<ConsumptionDetail> ConsumptionDetails { get; set; }
        public virtual User User { get; set; }
    }
}
