//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCenter
    {
        public CostCenter()
        {
            this.Consumers = new HashSet<Consumer>();
            this.CostCenters1 = new HashSet<CostCenter>();
        }
    
        public int IDCostCenter { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Code { get; set; }
        public Nullable<int> IDParentCostCenter { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<Consumer> Consumers { get; set; }
        public virtual ICollection<CostCenter> CostCenters1 { get; set; }
        public virtual CostCenter CostCenter1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
