//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationsToUser
    {
        public int IDNotificationToUser { get; set; }
        public int IDNotification { get; set; }
        public int IDUser { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> DateRead { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
    }
}
