//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationRule
    {
        public NotificationRule()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int IDNotificationRule { get; set; }
        public string RuleDescription { get; set; }
        public string SPToExecute { get; set; }
        public string NotificationSubject { get; set; }
        public string NotificationBody { get; set; }
        public int ValidityDays { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual NotificationRule NotificationRules1 { get; set; }
        public virtual NotificationRule NotificationRule1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
