//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportsToRole
    {
        public int IDReportToRole { get; set; }
        public int IDReport { get; set; }
        public int IDRole { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Active { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual Role Role { get; set; }
    }
}
