//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.MenuToRoles = new HashSet<MenuToRole>();
            this.ReportsToRoles = new HashSet<ReportsToRole>();
            this.UsersToRoles = new HashSet<UsersToRole>();
        }
    
        public int IDRole { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<MenuToRole> MenuToRoles { get; set; }
        public virtual ICollection<ReportsToRole> ReportsToRoles { get; set; }
        public virtual ICollection<UsersToRole> UsersToRoles { get; set; }
    }
}
