//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Assets = new HashSet<Asset>();
            this.Assets1 = new HashSet<Asset>();
            this.ConsumerTypesToReports = new HashSet<ConsumerTypesToReport>();
            this.ConsumptionDetails = new HashSet<ConsumptionDetail>();
            this.ConsumptionDetails1 = new HashSet<ConsumptionDetail>();
            this.Consumptions = new HashSet<Consumption>();
            this.CostCenters = new HashSet<CostCenter>();
            this.CostCenters1 = new HashSet<CostCenter>();
            this.Imports = new HashSet<Import>();
            this.Locations = new HashSet<Location>();
            this.Locations1 = new HashSet<Location>();
            this.Menus = new HashSet<Menu>();
            this.Menus1 = new HashSet<Menu>();
            this.MenuToRoles = new HashSet<MenuToRole>();
            this.MenuToRoles1 = new HashSet<MenuToRole>();
            this.NotificationRules = new HashSet<NotificationRule>();
            this.NotificationRules1 = new HashSet<NotificationRule>();
            this.NotificationsToUsers = new HashSet<NotificationsToUser>();
            this.Reports = new HashSet<Report>();
            this.UsersToRoles = new HashSet<UsersToRole>();
            this.UsersToRoles1 = new HashSet<UsersToRole>();
        }
    
        public int IDUser { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual ICollection<Asset> Assets1 { get; set; }
        public virtual ICollection<ConsumerTypesToReport> ConsumerTypesToReports { get; set; }
        public virtual ICollection<ConsumptionDetail> ConsumptionDetails { get; set; }
        public virtual ICollection<ConsumptionDetail> ConsumptionDetails1 { get; set; }
        public virtual ICollection<Consumption> Consumptions { get; set; }
        public virtual ICollection<CostCenter> CostCenters { get; set; }
        public virtual ICollection<CostCenter> CostCenters1 { get; set; }
        public virtual ICollection<Import> Imports { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Location> Locations1 { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Menu> Menus1 { get; set; }
        public virtual ICollection<MenuToRole> MenuToRoles { get; set; }
        public virtual ICollection<MenuToRole> MenuToRoles1 { get; set; }
        public virtual ICollection<NotificationRule> NotificationRules { get; set; }
        public virtual ICollection<NotificationRule> NotificationRules1 { get; set; }
        public virtual ICollection<NotificationsToUser> NotificationsToUsers { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<UsersToRole> UsersToRoles { get; set; }
        public virtual ICollection<UsersToRole> UsersToRoles1 { get; set; }
    }
}
