//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerType
    {
        public ConsumerType()
        {
            this.Consumers = new HashSet<Consumer>();
            this.ConsumerTypesToReports = new HashSet<ConsumerTypesToReport>();
        }
    
        public int IDConsumerType { get; set; }
        public string ConsumerTypeName { get; set; }
        public string MapType { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Consumer> Consumers { get; set; }
        public virtual ICollection<ConsumerTypesToReport> ConsumerTypesToReports { get; set; }
    }
}
