//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GisDB : DbContext
    {
        public GisDB()
            : base("name=GisDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcquisitionPrice> AcquisitionPrices { get; set; }
        public DbSet<Asset> Assets { get; set; }
        public DbSet<Consumer> Consumers { get; set; }
        public DbSet<ConsumerType> ConsumerTypes { get; set; }
        public DbSet<ConsumerTypesToReport> ConsumerTypesToReports { get; set; }
        public DbSet<ConsumptionDetail> ConsumptionDetails { get; set; }
        public DbSet<Consumption> Consumptions { get; set; }
        public DbSet<CostCenter> CostCenters { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<ElectricStation> ElectricStations { get; set; }
        public DbSet<FieldCluster> FieldClusters { get; set; }
        public DbSet<ImportFile> ImportFiles { get; set; }
        public DbSet<Import> Imports { get; set; }
        public DbSet<ImportType> ImportTypes { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MenuToRole> MenuToRoles { get; set; }
        public DbSet<Month> Months { get; set; }
        public DbSet<NetworkOperator> NetworkOperators { get; set; }
        public DbSet<NotificationRule> NotificationRules { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<NotificationsToUser> NotificationsToUsers { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<ReportsToRole> ReportsToRoles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersToRole> UsersToRoles { get; set; }
        public DbSet<VoltageLevel> VoltageLevels { get; set; }
    }
}
