//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int IDLocation { get; set; }
        public int IDConsumer { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public Nullable<int> ElectricalLineDiagramX { get; set; }
        public Nullable<int> ElectricalLineDiagramY { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
