//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationsToUsers = new HashSet<NotificationsToUser>();
        }
    
        public int IDNotification { get; set; }
        public Nullable<int> IDNotificationRule { get; set; }
        public string NotificationSubject { get; set; }
        public string NotificationBody { get; set; }
        public System.DateTime NotificationStartDate { get; set; }
        public System.DateTime NotificationEndDate { get; set; }
        public bool Active { get; set; }
    
        public virtual NotificationRule NotificationRule { get; set; }
        public virtual ICollection<NotificationsToUser> NotificationsToUsers { get; set; }
    }
}
