//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.ConsumerTypesToReports = new HashSet<ConsumerTypesToReport>();
            this.ReportsToRoles = new HashSet<ReportsToRole>();
        }
    
        public int IDReport { get; set; }
        public string ReportName { get; set; }
        public string UIReportName { get; set; }
        public string ReportGroup { get; set; }
        public int ReportGroupOrderNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ConsumerTypesToReport> ConsumerTypesToReports { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ReportsToRole> ReportsToRoles { get; set; }
    }
}
